## **Aljabar Matriks**

Matriks sendiri merupakan kumpulan bilangan yang disusun berdasarkan urutan baris dan kolom, serta dibatasi oleh tanda kurung.

1. Matriks yang mempunyai 1 kolom dinamakan vektor
2. untuk menyatakan nama matriks biasanya dengan huruf besar
3. Ukuran matriks tergantung pada jumlah baris dan kolom, seperti matriks dibawah ini

In [4]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]]) # 3x3 
B = np.array ([[1,4,6],[4,2,8],[6,2,4]]) # 3x3
C = np.array ([[2,3],[4,6],[4,2]])       # 3x2
D = np.array ([[2,4,5],[3,6,8],[5,4,9]]) # 3x3
print(C.shape)

# indeks 0 merupakan jumlah baris
# indeks 1 merupakan jumlah kolom

(3, 2)


In [9]:
# Cara membuat matriks dengan cepat menggunakan bilangan yang random

#A = np.random.randint(10,size=(3,3))
#print(A)

A = np.random.randint(10,size=(3,3)) # 10 merupakan bilangan yang akan dipakai yaitu mulai dari 0-10, size menunjukkan ukuran untuk jumlah kolom dan baris
print(A)

[[4 8 2]
 [0 7 2]
 [4 8 4]]


## **Operasi-operasi matriks**

Dalam aljabar matriks ada tiga dasar yang sering digunakan yaitu

**1. Penjumlahan matriks**

Dua matriks dengan ukuran yang sama lalu dijumlahkan, hasil dari matriks adalah penjumlahan setiap elemen dari dua buah matriks.
 
Misalnya, jika A dan B adalah matriks m x n, maka penjumlahannya adalah:

   \[ $A + B = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{bmatrix} + \begin{bmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{bmatrix} = \begin{bmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{bmatrix}$ \]

**Contoh implementasi dengan numpy**

In [1]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]]) # 3x3 
B = np.array ([[1,4,6],[4,2,8],[6,2,4]]) # 3x3
C = np.array ([[2,3],[4,6],[4,2]])       # 3x2
D = np.array ([[2,4,5],[3,6,8],[5,4,9]]) # 3x3

print(A+B)

[[ 2  6 10]
 [ 6  5 14]
 [ 9  3  9]]


**2. Perkalian matriks**

A adalah matriks berukuran m x n (m baris dan n kolom), dan B adalah matriks berukuran n x k (n baris dan k kolom). Maka, hasil perkalian A dan B akan menghasilkan matriks C berukuran m x k.
    
Untuk mendapatkan elemen c_{ij} dari matriks C, kita mengalikan setiap elemen a_{ir} dari baris i dari matriks A dengan setiap elemen b_{rj} dari kolom j dari matriks B, kemudian menjumlahkan hasilnya untuk r dari 1 hingga n. Secara matematis, elemen c_{ij} dari matriks C.

   Misalnya, jika A adalah matriks m x n, B adalah matriks n x k, dan C adalah matriks m x k untuk rumus penyelesaiannya adalah:

   \[ $A \cdot B = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \end{bmatrix} \cdot \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \\ b_{31} & b_{32} \end{bmatrix} = \begin{bmatrix} a_{11}b_{11} + a_{12}b_{21} + a_{13}b_{31} & a_{11}b_{12} + a_{12}b_{22} + a_{13}b_{32} \\ a_{21}b_{11} + a_{22}b_{21} + a_{23}b_{31} & a_{21}b_{12} + a_{22}b_{22} + a_{23}b_{32} \end{bmatrix}$ \]

**Contoh implementasi dengan numpy**

In [3]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]]) # 3x3 
B = np.array ([[1,4,6],[4,2,8],[6,2,4]]) # 3x3
C = np.array ([[2,3],[4,6],[4,2]])       # 3x2
D = np.array ([[2,4,5],[3,6,8],[5,4,9]]) # 3x3

c = np.dot(A,B)
print(c)

[[33 16 38]
 [50 26 60]
 [37 24 46]]


**3. Perkalian dengan Skalar**

 Setiap elemen dari matriks dikalikan dengan skalar tersebut. Hasilnya adalah matriks baru yang memiliki ukuran yang sama dengan matriks asal, di mana setiap elemen baru dihasilkan dari perkalian elemen yang sesuai dengan skalar.

   Misalnya, jika C adalah matriks m x n dan c adalah suatu bilangan, maka untuk rumus penyelesaiannya adalah:

   \[ $c \cdot C = \begin{bmatrix} c \cdot c_{11} & c \cdot c_{12} & \cdots & c \cdot c_{1n} \\ c \cdot c_{21} & c \cdot c_{22} & \cdots & c \cdot c_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ c \cdot c_{m1} & c \cdot c_{m2} & \cdots & c \cdot c_{mn} \end{bmatrix}$ \]


**Contoh implementasi dengan numpy**

In [2]:
import numpy as np

A = np.array([[1, 2, 4], [2, 3, 6], [3, 1, 5]])  # Matriks A berukuran 3x3
B = np.array([[1, 4, 6], [4, 2, 8], [6, 2, 4]])  # Matriks B berukuran 3x3
c = 2  # Skalar c

# Perkalian matriks A dengan skalar c
skalar = c * A
print(skalar)

# Perkalian matriks B dengan skalar c
skalar = c * B
print(skalar)


[[ 2  4  8]
 [ 4  6 12]
 [ 6  2 10]]
[[ 2  8 12]
 [ 8  4 16]
 [12  4  8]]


## **Matriks Tranpose**

Matriks tranpose biasanya dilambangkan dengan 

$A^T$, 
$A'$

matriks tranpose adalah sebuah matriks yang mengubah baris menjadi kolom dan kolom menjadi baris, Misalnya saya mempunyai matriks A yang berukuran  $m$ x $n$ maka hasil untuk matriks tranpose $A^T$ berukuran $n$ x $m$.


**Contoh implementasi dengan numpy**

In [4]:
A_T = A.transpose()
print(A)
print(" ")
print(A_T)

[[1 2 4]
 [2 3 6]
 [3 1 5]]
 
[[1 2 3]
 [2 3 1]
 [4 6 5]]


In [3]:
C = np.array ([[2,3],[4,6],[4,2]])

C_T = C.transpose()
print(C)
print('\n')
print(C_T)

[[2 3]
 [4 6]
 [4 2]]


[[2 4 4]
 [3 6 2]]


In [5]:
import numpy as np
A = np.array ([[1,2,4],[2,3,6],[3,1,5]]) 
B = np.array ([[1,4,6],[4,2,8],[6,2,4]]) 
C = np.array ([[2,3],[4,6],[4,2]])       
D = np.array ([[2,4,5],[3,6,8],[5,4,9]]) 
t = A*B*D
print(t)
print(" ")
tt = t.transpose()
print(tt)
print(" ")
print(" ")
a = A.transpose()
b = B.transpose()
dd = D.transpose()
print(a*b*dd)
print(" ")
print(" ")
abd = (A+B)*D
ABD = abd.transpose()
print(ABD)
print(" ")
print(" ")
abc = (A+B)*C
ABC = abc.transpose()
print(ABC)

[[  2  32 120]
 [ 24  36 384]
 [ 90   8 180]]
 
[[  2  24  90]
 [ 32  36   8]
 [120 384 180]]
 
 
[[  2  24  90]
 [ 32  36   8]
 [120 384 180]]
 
 
[[  4  18  45]
 [ 24  30  12]
 [ 50 112  81]]
 
 


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

## **Matriks Elementer**

Matriks ini merupakan matriks yang memiliki semua elemen sama, kecuali untuk elemen di sepanjang diagonal utamanya, yang memiliki nilai yang berbeda.

Operasi yang akan digunakan dalam menentukan matriks elementer sebagai berikut:
1. mengalikan baris dengan bilangan tak nol
2. menambahkan kelipatan suatu baris pada baris yang lain
3. menukarkan sebarang dua buah baris 

**Berikut adalah contoh kode Python yang mengalikan dua matrix menggunakan perulangan**

In [7]:

def multiply_matrices(matrix1, matrix2):
    # Mengecek apakah kedua matriks bisa dikalikan
    if len(matrix1[0]) != len(matrix2):
        print("Error: Jumlah kolom matriks pertama tidak sama dengan jumlah baris matriks kedua.")
        return None

    # Menginisialisasi matriks hasil
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]

    # Perulangan untuk mengalikan matriks
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

# Contoh penggunaan
matrix1 = [[1, 2, 3], [4, 5, 6]]
matrix2 = [[7, 8], [9, 10], [11, 12]]

result = multiply_matrices(matrix1, matrix2)
if result:
    print("Hasil perkalian matriks:")
    for row in result:
        print(row)




Hasil perkalian matriks:
[58, 64]
[139, 154]
