## **Determinan**

Determinan adalah ukuran skalar dari semua matriks dan berlaku untuk matriks bujur sangkar. example: $A_nx_n$

## Sifat-Sifat Determinan

## 1. Determinan dari matriks identitas adalah 1.example:


In [2]:
import numpy as np
A = np.array([[3,6],[6,2]])
B = np.array([[2,5,3],[7,2,3],[1,6,9]])
C = np.array([[1,0],[0,1]])
D = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(A)
print(B)
print(C)
print(D)

np.linalg.det(A)
np.linalg.det(B)
np.linalg.det(C)
np.linalg.det(D)

[[3 6]
 [6 2]]
[[2 5 3]
 [7 2 3]
 [1 6 9]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


1.0

## 2. Determinan dari matriks AB sama dengan determinan matriks A dikali determinan matriks B.

$det(AB) = det(A).det(B)$

Jika $I=A.A^{-1}$ maka $det(I)=det(A).det(A^{-1})$.
Sehingga, $det(A^{-1})=\frac{1}{det(A)}$

In [3]:
def RowSwap(A,k,l):
    # =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [4]:
print(A)
print(C)

[[3 6]
 [6 2]]
[[1 0]
 [0 1]]


In [5]:
import numpy as np

# Buat array NumPy
A = np.array([[3, 6], [6, 2]])

# Swap baris pertama dengan baris kedua
A = RowSwap(A, 0, 1)

# Scale baris pertama dengan faktor 1/3
A = RowScale(A, 0, 1/3)

# Add baris pertama ke baris kedua dengan faktor -2
A = RowAdd(A, 0, 1, -2)

print("Matriks identitas:")
print(A)


Matriks identitas:
[[ 2.          0.66666667]
 [-1.          4.66666667]]


In [6]:
E = np.array([[3,5,1],[2,6,2],[1,3,1]])
F = np.array([[1,1,2],[1,1,3],[2,1,2]])
g = E@F
print(E)
e = np.linalg.det(E)
print(e)
print(F)
f = np.linalg.det(F)
print(f)

[[3 5 1]
 [2 6 2]
 [1 3 1]]
0.0
[[1 1 2]
 [1 1 3]
 [2 1 2]]
1.0


## 3. Penukaran kolom atau baris akan mengubah tanda determinan

In [7]:
a = np.array([[1,4,2],[1,1,1],[3,2,1]])
print(a)
round(np.linalg.det(a))

[[1 4 2]
 [1 1 1]
 [3 2 1]]


5

In [9]:
a1 = RowSwap(a,0,1)
print(a1)
round(np.linalg.det(a1))

[[1. 1. 1.]
 [1. 4. 2.]
 [3. 2. 1.]]


-5

In [10]:
a2 = np.array([[1,2,4],[1,1,1],[3,1,2]])
print(a)
round(np.linalg.det(a1))

[[1 4 2]
 [1 1 1]
 [3 2 1]]


-5

# 4. Jika nilai-nilai suatu baris atau kolom pada sebuah matriks merupakan kelipatan dari nilai-nilai baris atau kolom lainnya, maka determinannya adalah 0.

In [17]:
a = np.array([[1,4,2],[2,8,4],[3,2,1]])
print(a)
round(np.linalg.det(a))

[[1 4 2]
 [2 8 4]
 [3 2 1]]


0

In [12]:
b = np.array([[1,4,2],[2,8,3],[1,4,1]])
print(b)
round(np.linalg.det(b))

[[1 4 2]
 [2 8 3]
 [1 4 1]]


0

# 5. Jika determinan skalar k dan determinan matriks $A_{n x n}$ dikalikan, maka $det(k.A)=k^n.det(A)$.

In [19]:
print(a)
print(round(np.linalg.det(a)))

[[1 4 2]
 [2 8 4]
 [3 2 1]]
0


In [20]:
b = np.array([[1,4,2],[2,8,3],[1,4,1]])
k = 2
print(b*k)

[[ 2  8  4]
 [ 4 16  6]
 [ 2  8  2]]


# 5. Melakukan operasi baris elementer terhadap matriks tidak akan mengubah determinan dan inversnya.

In [21]:
B = np.array([[1,4,2],[0,-3,-1],[3,2,1]])
print(B)
print(round(np.linalg.det(B)))

[[ 1  4  2]
 [ 0 -3 -1]
 [ 3  2  1]]
5


# 6. Determinan Transpose matriks A sama dengan determinan matriks A

In [22]:
A = np.array([[1,1,3],[4,1,2],[2,1,1]])
print(A)
print(round(np.linalg.det(A)))

[[1 1 3]
 [4 1 2]
 [2 1 1]]
5


In [23]:
A1 = np.transpose(A)
print(A1)
print(round(np.linalg.det(A1)))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
5


# Matriks Segitiga Atas

In [24]:
A = np.array([[2,3,1,2],[0,1,2,1],[0,0,5,2],[0,0,0,3]])
print(A)
print(round(np.linalg.det(A)))

[[2 3 1 2]
 [0 1 2 1]
 [0 0 5 2]
 [0 0 0 3]]
30


In [25]:
A = np.array([[1,4,2],[0,4,1],[0,0,1]])
print(A)
print(round(np.linalg.det(A)))

[[1 4 2]
 [0 4 1]
 [0 0 1]]
4


In [26]:
A = np.array([[4,2],[0,1]])
print(A)
print(round(np.linalg.det(A)))

[[4 2]
 [0 1]]
4


## Ekspansi Kofaktor

Ekspansi kofaktor adalah salah satu metode yang digunakan untuk menghitung determinan dari sebuah matriks. Berikut adalah langkah-langkah umum untuk menghitung determinan menggunakan ekspansi kofaktor:

1. Pilih baris atau kolom tertentu dari matriks yang akan digunakan untuk menghitung determinan. Misalnya, pilih baris pertama atau kolom pertama.

2. Untuk setiap elemen dalam baris atau kolom yang dipilih, hitung kofaktornya. Kofaktor dari elemen \( $a_{ij}$ \) adalah \( $(-1)^{i+j}$ \) dikalikan dengan determinan dari minor \( $M_{ij}$ \), di mana minor \( $M_{ij}$ \) adalah matriks yang dihasilkan dari matriks asli dengan menghapus baris ke-i dan kolom ke-j.

3. Kalikan setiap kofaktor dengan elemen yang bersangkutan, kemudian tambahkan semua hasil perkalian tersebut. Ini akan memberikan nilai determinan dari matriks.

Nb : Langkah-langkah ini dapat diulang untuk setiap baris atau kolom matriks hingga determinan lengkapnya terhitung. 

## tugas : proses menghitung determinan matriks 4x4 bebas menggunakan ekspansi kofaktor

contoh matriks 4x4  untuk menghitung determinannya menggunakan ekspansi kofaktor:


\[
$A = \begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}$
\]




menghitung determinan matriks \(A\) dengan menggunakan rumus ekspansi kofaktor:


$\text{det}(A) = 1 \times C_{11} - 2 \times C_{12} + 3 \times C_{13} - 4 \times C_{14}$


perhitungan determinan untuk matriks \(A\) dengan menggunakan ekspansi kofaktor.



$\begin{align}
C_{11} & = 6 \times \text{det} \begin{vmatrix} 11 & 12 \\ 15 & 16 \end{vmatrix} - 7 \times \text{det} \begin{vmatrix} 10 & 12 \\ 14 & 16 \end{vmatrix} + 8 \times \text{det} \begin{vmatrix} 10 & 11 \\ 14 & 15 \end{vmatrix} \\
& = 6 \times ((11 \times 16) - (12 \times 15)) - 7 \times ((10 \times 16) - (12 \times 14)) + 8 \times ((10 \times 15) - (11 \times 14)) \\
& = 6 \times (176 - 180) - 7 \times (160 - 168) + 8 \times (150 - 154) \\
& = 6 \times (-4) - 7 \times (-8) + 8 \times (-4) \\
& = -24 + 56 - 32 \\
& = 0
\end{align}$



$\begin{align}
C_{12} & = -5 \times \text{det} \begin{vmatrix} 11 & 12 \\ 15 & 16 \end{vmatrix} + 7 \times \text{det} \begin{vmatrix} 9 & 12 \\ 13 & 16 \end{vmatrix} - 8 \times \text{det} \begin{vmatrix} 9 & 11 \\ 13 & 15 \end{vmatrix} \\
& = -5 \times ((11 \times 16) - (12 \times 15)) + 7 \times ((9 \times 16) - (12 \times 13)) - 8 \times ((9 \times 15) - (11 \times 13)) \\
& = -5 \times (176 - 180) + 7 \times (144 - 156) - 8 \times (135 - 143) \\
& = -5 \times (-4) + 7 \times (-12) - 8 \times (-8) \\
& = 20 - 84 + 64 \\
& = 0
\end{align}$


$\begin{align}
C_{13} & = 9 \times \text{det} \begin{vmatrix} 7 & 8 \\ 11 & 12 \end{vmatrix} - 10 \times \text{det} \begin{vmatrix} 6 & 8 \\ 10 & 12 \end{vmatrix} + 11 \times \text{det} \begin{vmatrix} 6 & 7 \\ 10 & 11 \end{vmatrix} \\
& = 9 \times ((7 \times 12) - (8 \times 11)) - 10 \times ((6 \times 12) - (8 \times 10)) + 11 \times ((6 \times 11) - (7 \times 10)) \\
& = 9 \times (84 - 88) - 10 \times (72 - 80) + 11 \times (66 - 70) \\
& = 9 \times (-4) - 10 \times (-8) + 11 \times (-4) \\
& = -36 + 80 - 44 \\
& = 0
\end{align}$



$\begin{align}
C_{14} & = -13 \times \text{det} \begin{vmatrix} 6 & 7 \\ 10 & 11 \end{vmatrix} + 14 \times \text{det} \begin{vmatrix} 5 & 7 \\ 9 & 11 \end{vmatrix} - 15 \times \text{det} \begin{vmatrix} 5 & 6 \\ 9 & 10 \end{vmatrix} \\
& = -13 \times ((6 \times 11) - (7 \times 10)) + 14 \times ((5 \times 11) - (7 \times 9)) - 15 \times ((5 \times 10) - (6 \times 9)) \\
& = -13 \times (66 - 70) + 14 \times (55 - 63) - 15 \times (50 - 54) \\
& = -13 \times (-4) + 14 \times (-8) - 15 \times (-4) \\
& = 52 - 112 + 60 \\
& = 0
\end{align}$


Sekarang  sudah memiliki nilai kofaktor untuk semua elemen. Selanjutnya, dapat menghitung determinan matriks \(A\) menggunakan rumus ekspansi kofaktor:


$\text{det}(A) = 1 \times C_{11} - 2 \times C_{12} + 3 \times C_{13} - 4 \times C_{14} = 0$


Jadi, determinan dari matriks \(A\) adalah 0.

$\begin{align}
C_{21} & = (-1)^{2+1} \times \text{det} \begin{vmatrix} 2 & 3 & 4 \\ 10 & 11 & 12 \\ 14 & 15 & 16 \end{vmatrix} = -2 \times \text{det} \begin{vmatrix} 11 & 12 \\ 15 & 16 \end{vmatrix} + 3 \times \text{det} \begin{vmatrix} 10 & 12 \\ 14 & 16 \end{vmatrix} - 4 \times \text{det} \begin{vmatrix} 10 & 11 \\ 14 & 15 \end{vmatrix} \\
& = -2 \times ((11 \times 16) - (12 \times 15)) + 3 \times ((10 \times 16) - (12 \times 14)) - 4 \times ((10 \times 15) - (11 \times 14)) \\
& = -2 \times (176 - 180) + 3 \times (160 - 168) - 4 \times (150 - 154) \\
& = -2 \times (-4) + 3 \times (-8) - 4 \times (-4) \\
& = 8 - 24 + 16 \\
& = 0
\end{align}$

$\begin{align}
C_{22} & = (-1)^{2+2} \times \text{det} \begin{vmatrix} 1 & 3 & 4 \\ 9 & 11 & 12 \\ 13 & 15 & 16 \end{vmatrix} = 1 \times \text{det} \begin{vmatrix} 9 & 12 \\ 13 & 16 \end{vmatrix} - 3 \times \text{det} \begin{vmatrix} 9 & 12 \\ 13 & 16 \end{vmatrix} + 4 \times \text{det} \begin{vmatrix} 9 & 11 \\ 13 & 15 \end{vmatrix} \\
& = 1 \times ((9 \times 16) - (12 \times 13)) - 3 \times ((9 \times 16) - (12 \times 13)) + 4 \times ((9 \times 15) - (11 \times 13)) \\
& = 1 \times (144 - 156) - 3 \times (144 - 156) + 4 \times (135 - 143) \\
& = 1 \times (-12) - 3 \times (-12) + 4 \times (-8) \\
& = -12 + 36 - 32 \\
& = -8
\end{align}$

$\begin{align}
C_{23} & = (-1)^{2+3} \times \text{det} \begin{vmatrix} 1 & 2 & 4 \\ 9 & 10 & 12 \\ 13 & 14 & 16 \end{vmatrix} = -1 \times \text{det} \begin{vmatrix} 9 & 12 \\ 13 & 16 \end{vmatrix} + 2 \times \text{det} \begin{vmatrix} 9 & 12 \\ 13 & 16 \end{vmatrix} - 4 \times \text{det} \begin{vmatrix} 9 & 10 \\ 13 & 14 \end{vmatrix} \\
& = -1 \times ((9 \times 16) - (12 \times 13)) + 2 \times ((9 \times 16) - (12 \times 13)) - 4 \times ((9 \times 14) - (10 \times 13)) \\
& = -1 \times (144 - 156) + 2 \times (144 - 156) - 4 \times (126 - 130) \\
& = -1 \times (-12) + 2 \times (-12) - 4 \times (-4) \\
& = 12 - 24 + 16 \\
& = 4
\end{align}$

$\begin{align}
C_{24} & = (-1)^{2+4} \times \text{det} \begin{vmatrix} 1 & 2 & 3 \\ 9 & 10 & 11 \\ 13 & 14 & 15 \end{vmatrix} = 1 \times \text{det} \begin{vmatrix} 9 & 10 \\ 13 & 14 \end{vmatrix} - 2 \times \text{det} \begin{vmatrix} 9 & 11 \\ 13 & 15 \end{vmatrix} + 3 \times \text{det} \begin{vmatrix} 9 & 11 \\ 13 & 15 \end{vmatrix} \\
& = 1 \times ((9 \times 14) - (10 \times 13)) - 2 \times ((9 \times 15) - (11 \times 13)) + 3 \times ((9 \times 15) - (10 \times 14)) \\
& = 1 \times (126 - 140) - 2 \times (135 - 143) + 3 \times (135 - 140) \\
& = 1 \times (-14) - 2 \times (-8) + 3 \times (-5) \\
& = -14 + 16 - 15 \\
& = -13
\end{align}$


$\begin{align}
C_{31} & = (-1)^{3+1} \times \text{det} \begin{bmatrix} 2 & 3 & 4 \\ 6 & 7 & 8 \\ 14 & 15 & 16 \end{bmatrix} = -1 \times \text{det} \begin{bmatrix} 6 & 7 \\ 14 & 15 \end{bmatrix} + 2 \times \text{det} \begin{bmatrix} 6 & 8 \\ 14 & 16 \end{bmatrix} - 3 \times \text{det} \begin{bmatrix} 6 & 8 \\ 14 & 16 \end{bmatrix} \\
& = -1 \times ((6 \times 15) - (7 \times 14)) + 2 \times ((6 \times 16) - (8 \times 14)) - 3 \times ((6 \times 16) - (8 \times 14)) \\
& = -1 \times (90 - 98) + 2 \times (96 - 112) - 3 \times (96 - 112) \\
& = -1 \times (-8) + 2 \times (-16) - 3 \times (-16) \\
& = 8 - 32 + 48 \\
& = 24
\end{align}$

$\begin{align}
C_{32} & = (-1)^{3+2} \times \text{det} \begin{bmatrix} 1 & 3 & 4 \\ 5 & 7 & 8 \\ 13 & 15 & 16 \end{bmatrix} = 1 \times \text{det} \begin{bmatrix} 5 & 8 \\ 13 & 16 \end{bmatrix} - 3 \times \text{det} \begin{bmatrix} 5 & 8 \\ 13 & 16 \end{bmatrix} + 4 \times \text{det} \begin{bmatrix} 5 & 7 \\ 13 & 15 \end{bmatrix} \\
& = 1 \times ((5 \times 16) - (8 \times 13)) - 3 \times ((5 \times 16) - (8 \times 13)) + 4 \times ((5 \times 15) - (7 \times 13)) \\
& = 1 \times (80 - 104) - 3 \times (80 - 104) + 4 \times (75 - 91) \\
& = 1 \times (-24) - 3 \times (-24) + 4 \times (-16) \\
& = -24 + 72 - 64 \\
& = -16
\end{align}$



$\begin{align}
C_{33} & = (-1)^{3+3} \times \text{det} \begin{bmatrix} 1 & 2 & 4 \\ 5 & 6 & 8 \\ 13 & 14 & 16 \end{bmatrix} = 1 \times \text{det} \begin{bmatrix} 5 & 6 \\ 13 & 14 \end{bmatrix}- 2 \times \text{det} \begin{bmatrix} 5 & 8 \\ 13 & 16 \end{bmatrix} + 4 \times \text{det} \begin{bmatrix} 5 & 8 \\ 13 & 16 \end{bmatrix} \\
& = 1 \times ((5 \times 14) - (6 \times 13)) - 2 \times ((5 \times 16) - (8 \times 13)) + 4 \times ((5 \times 16) - (8 \times 13)) \\
& = 1 \times (70 - 78) - 2 \times (80 - 104) + 4 \times (80 - 104) \\
& = 1 \times (-8) - 2 \times (-24) + 4 \times (-24) \\
& = -8 + 48 - 96 \\
& = -56
\end{align}$


\begin{align}
C_{34} & = (-1)^{3+4} \times \text{det} \begin{bmatrix} 1 & 2 & 3 \\ 5 & 6 & 7 \\ 13 & 14 & 15 \end{bmatrix} = -1 \times \text{det} \begin{bmatrix} 5 & 6 \\ 13 & 14 \end{bmatrix} + 2 \times \text{det} \begin{bmatrix} 5 & 7 \\ 13 & 15 \end{bmatrix} - 3 \times \text{det} \begin{bmatrix} 5 & 7 \\ 13 & 15 \end{bmatrix} \\
& = -1 \times ((5 \times 14) - (6 \times 13)) + 2 \times ((5 \times 15) - (7 \times 13)) - 3 \times ((5 \times 15) - (7 \times 13)) \\
& = -1 \times (70 - 78) + 2 \times (75 - 91)

- 3 \times (75 - 91) \\
& = -1 \times (-8) + 2 \times (-16) - 3 \times (-16) \\
& = 8 - 32 + 48 \\
& = 24
\end{align}




$\begin{align}
C_{41} & = (-1)^{4+1} \times \text{det} \begin{bmatrix} 2 & 3 & 4 \\ 6 & 7 & 8 \\ 10 & 11 & 12 \end{bmatrix} = 1 \times \text{det} \begin{bmatrix} 6 & 7 \\ 10 & 11 \end{bmatrix} - 2 \times \text{det} \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix} + 3 \times \text{det} \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix} \\
& = 1 \times ((6 \times 11) - (7 \times 10)) - 2 \times ((6 \times 12) - (8 \times 10)) + 3 \times ((6 \times 12) - (8 \times 10)) \\
& = 1 \times (66 - 70) - 2 \times (72 - 80) + 3 \times (72 - 80) \\
& = 1 \times (-4) - 2 \times (-8) + 3 \times (-8) \\
& = -4 + 16 - 24 \\
& = -12
\end{align}$

$\begin{align}
C_{42} & = (-1)^{4+2} \times \text{det} \begin{bmatrix} 1 & 3 & 4 \\ 5 & 7 & 8 \\ 9 & 11 & 12 \end{bmatrix} = -1 \times \text{det} \begin{bmatrix} 5 & 8 \\ 9 & 12 \end{bmatrix} + 2 \times \text{det} \begin{bmatrix} 5 & 8 \\ 9 & 12 \end{bmatrix} - 3 \times \text{det} \begin{bmatrix} 5 & 7 \\ 9 & 11 \end{bmatrix} \\
& = -1 \times ((5 \times 12) - (8 \times 9)) + 2 \times ((5 \times 12) - (8 \times 9)) - 3 \times ((5 \times 11) - (7 \times 9)) \\
& = -1 \times (60 - 72) + 2 \times (60 - 72) - 3 \times (55 - 63) \\
& = -1 \times (-12) + 2 \times (-12) - 3 \times (-8) \\
& = 12 - 24 + 24 \\
& = 12
\end{align}$

$\begin{align}
C_{43} & = (-1)^{4+3} \times \text{det} \begin{bmatrix} 1 & 2 & 4 \\ 5 & 6 & 8 \\ 9 & 10 & 12 \end{bmatrix} = 1 \times \text{det} \begin{bmatrix} 5 & 6 \\ 9 & 10 \end{bmatrix} - 2 \times \text{det} \begin{bmatrix} 5 & 8 \\ 9 & 12 \end{bmatrix} + 3 \times \text{det} \begin{bmatrix} 5 & 8 \\ 9 & 12 \end{bmatrix} \\
& = 1 \times ((5 \times 10) - (6 \times 9)) - 2 \times ((5 \times 12) - (8 \times 9)) + 3 \times ((5 \times 12) - (8 \times 9)) \\
& = 1 \times (50 - 54) - 2 \times (60 - 72) + 3 \times (60 - 72) \\
& = 1 \times (-4) - 2 \times (-12) + 3 \times (-12) \\
& = -4 + 24 - 36 \\
& = -16
\end{align}$

$\begin{align}
C_{44} & = (-1)^{4+4} \times \text{det} \begin{bmatrix} 1 & 2 & 3 \\ 5 & 6 & 7 \\ 9 & 10 & 11 \end{bmatrix} = -1 \times \text{det} \begin{bmatrix} 5 & 6 \\ 9 & 10 \end{bmatrix} + 2 \times \text{det} \begin{bmatrix} 5 & 7 \\ 9 & 11 \end{bmatrix} - 3 \times \text{det} \begin{bmatrix} 5 & 7 \\ 9 & 11 \end{bmatrix} \\
& = -1 \times ((5 \times 10) - (6 \times 9)) + 2 \times ((5 \times 11) - (7 \times 9)) - 3 \times ((5 \times 11) - (7 \times 9)) \\
& = -1 \times (50 - 54) + 2 \times (55 - 63) - 3 \times (55 - 63) \\
& = -1 \times (-4) + 2 \times (-8) - 3 \times (-8) \\
& = 4 - 16 + 24 \\
& = 12
\end{align}$

menghitung kofaktor untuk semua elemen, sekarang dapat menghitung determinan dari matriks \(A\). menggunakan rumus ekspansi kofaktor:


$\text{det}(A) = \sum_{j=1}^{n} a_{ij} \times C_{ij}$


dengan \($n$\) adalah ukuran matriks dan \($a_{ij}$\) adalah elemen matriks pada baris ke-\(i\) dan kolom ke-\(j\), sedangkan \($C_{ij}$\) adalah kofaktor yang sesuai dengan elemen tersebut.

Untuk matriks \($4 \times 4$\), kita memiliki:


$\text{det}(A) = 1 \times C_{11} - 2 \times C_{12} + 3 \times C_{13} - 4 \times C_{14}$

= $1 \times 0 - 2 \times (-16) + 3 \times (-56) - 4 \times 24$

= $0 + 32 - 168 - 96$

= $-232$


Jadi, determinan dari matriks \($A$\) adalah \($-232$\).