## **Eigen Value dan Eigen Vector**


## **Konsep Eigen Value dan Eigen Vector**

Eigen Value dan Eigen Vector adalah sebuah konsep fundamental yang ada dalam aljabar linear dimana memiliki aplikasi luas dalam berbagai bidang, termasuk pemrosesan sinyal, mekanika struktural, dan pembelajaran mesin. Dan ini ada beberapa penjelasan tentang konsepnya:

# Eigen Value (Nilai Eigen)
Eigenvalue adalah angka yang memberi tahu seberapa banyak panjang eigenvector berubah ketika dikalikan dengan matriks tersebut. Eigenvalue juga sebuah angka yang menunjukkan berapa kali panjang panah berubah setelah transformasi. Misalnya, jika eigenvalue adalah 2, panjang panah menjadi dua kali lipat. 

# Eigen Vector (Vector Eigen)
Eigenvector adalah sebuah vektor yang, ketika dikalikan dengan sebuah matriks, tidak mengubah arah. Jadi, jika mengubahnya dengan menggunakan matriks, vektor ini akan tetap menunjuk ke arah yang sama, meskipun panjangnya bisa berubah. Jika panah tersebut adalah eigenvector, arah panah tetap sama setelah transformasi, hanya panjangnya yang mungkin berubah.

### Keterkaitan antara Eigenvector dan Eigenvalue
Secara matematis, jika \( A \) adalah matriks persegi \( $n \times n$ \), \( $\lambda$ \) adalah eigenvalue, dan \( $\mathbf{v}$ \) adalah eigenvector yang bersesuaian, maka mereka terkait melalui persamaan:

\[ $A \mathbf{v} = \lambda \mathbf{v}$ \]

Ini berarti ketika matriks \( A \) diaplikasikan pada eigenvector \( $\mathbf{v}$ \), hasilnya adalah eigenvector \( $\mathbf{v}$ \) yang sama, tetapi diperbesar atau diperkecil oleh faktor \($ \lambda$ \) (eigenvalue).

## Proses Mencari Eigenvalues dan Eigenvectors 

**1. Mencari Eigenvalues:**
   - Untuk menemukan eigenvalues (nilai eigen), kita harus menyelesaikan suatu persamaan khusus yang disebut persamaan karakteristik.
   - Persamaan ini dibuat dengan menghitung determinan dari matriks \( $A$ \) yang sudah dikurangi dengan \( $\lambda$ \) dikali matriks identitas \( $I$ \). 
   - Secara matematis, kita menuliskannya sebagai:
     \[ $\text{det}(A - \lambda I) = 0$ \]
   - Matriks identitas \( $I$ \) adalah matriks yang memiliki angka 1 di diagonal utamanya dan 0 di tempat lain.
   - Hasilnya adalah persamaan polinomial dalam \( $\lambda$ \). Akar-akar dari persamaan ini adalah eigenvalues dari matriks \( $A$ \).

**2.  Mencari Eigenvectors:**
   - Setelah kita menemukan eigenvalues, langkah berikutnya adalah mencari eigenvector (vektor eigen).
   - Untuk setiap eigenvalue \( $\lambda$ \), kita masukkan \( $\lambda$ \) ke dalam persamaan berikut:
     \[ $(A - \lambda I) \mathbf{v} = 0$ \]
   - Di sini, kita mencari vektor \( $\mathbf{v}$ \) yang tidak nol yang membuat persamaan ini benar.
   - Artinya, kita menyelesaikan sistem persamaan linear yang dihasilkan untuk menemukan eigenvector \( $\mathbf{v}$ \) yang bersesuaian dengan eigenvalue tersebut.

## Matriks 2x2
**1. Eigenvalues (Nilai Eigen):**

   Eigenvalues dari matriks 2x2 \( $A$ \) dapat ditemukan dengan menyelesaikan persamaan karakteristik \( $\text{det}(A - \lambda I) = 0$ \), di mana \( $I$ \) adalah matriks identitas 2x2 dan \( $\lambda$ \) adalah eigenvalue yang dicari. Persamaan karakteristik untuk matriks 2x2 \($ A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$ \) adalah \( $\text{det}\left(\begin{pmatrix} a-\lambda & b \\ c & d-\lambda \end{pmatrix}\right) = (a-\lambda)(d-\lambda) - bc = 0$ \). Solusi dari persamaan ini memberikan dua nilai eigenvalues.

**2. Eigenvectors (Vektor Eigen):**

   Eigenvectors adalah vektor-vektor yang, ketika dikalikan dengan matriks 2x2 \($A$ \), hanya mengalami perubahan skala (memanjang atau memendek) dan tidak mengalami perubahan arah. Untuk menemukan eigenvectors, kita substitusikan setiap eigenvalue ke dalam persamaan \( $(A - \lambda I) \mathbf{v} = 0$ \), di mana \( $\mathbf{v}$ \) adalah vektor eigen yang kita cari. Solusi dari persamaan ini memberikan eigenvectors yang bersesuaian.

## Matriks 3x3
**1. Eigenvalues:**

   Eigenvalues dari matriks 3x3 \( $A$ \) ditemukan dengan menyelesaikan persamaan karakteristik \( $\text{det}(A - \lambda I) = 0$ \), di mana \( $I$ \) adalah matriks identitas 3x3 dan \( $\lambda$ \) adalah eigenvalue yang dicari. Persamaan ini akan menghasilkan persamaan kubik dalam \( $\lambda$ \), yang memiliki tiga solusi eigenvalues.

**2. Eigenvectors:**

   Eigenvectors dari matriks 3x3 adalah vektor-vektor yang, ketika dikalikan dengan matriks 3x3 \( $A$ \), hanya mengalami perubahan skala dan tidak mengalami perubahan arah. Untuk setiap eigenvalue yang ditemukan, kita substitusikan ke dalam persamaan \( $(A - \lambda I) \mathbf{v} = 0$ \) untuk mencari vektor eigen yang sesuai. Ini akan menghasilkan sistem persamaan linear yang harus diselesaikan untuk mendapatkan eigenvectors.


## **Contoh Menghitung EigenValue dan EigenVector Menggunakan Numpy**

Matriks 2x2

In [1]:
import numpy as np
from numpy.linalg import eig

# Matriks 2x2
A = np.array([[1,4],[2,3]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w, '\n')
print('E-value', v.round(), '\n')

[[1 4]
 [2 3]] 

E-value [-1.  5.] 

E-value [[-1. -1.]
 [ 0. -1.]] 



Matriks 3x3

In [2]:
import numpy as np
from numpy.linalg import eig

# Matriks 3x3
A = np.array([[1,4,1],[2,3,2],[2,4,5]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w.round(), '\n')
print('E-value', v.round(), '\n')

[[1 4 1]
 [2 3 2]
 [2 4 5]] 

E-value [ 8. -1.  2.] 

E-value [[-0. -1. -1.]
 [-0.  0. -0.]
 [-1.  0.  1.]] 



## **Contoh Implementasi Eigenvalue dan EigenVector** 

Implementasi PCA melalui EVD dengan python:

In [3]:
import numpy as np

def pcaSVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)  # Pusatkan data

    u, sigma, vt = np.linalg.svd(X_centered, full_matrices=False)

    # Mengembalikan komponen utama dan eigenvalue
    return (X_centered @ vt.T), (sigma**2) / (n-1)

# Data contoh
x = np.array([[1, 4], [2, 3]])

komponen_utama, eigenvalue = pcaSVD(x)
print("Komponen utama:\n", komponen_utama.round())
print("Eigenvalue:\n", eigenvalue.round())


Komponen utama:
 [[-1.  0.]
 [ 1. -0.]]
Eigenvalue:
 [1. 0.]


  * Terdapat fungsi pcaEVD dengan parameter x.
  * n, p = X.shape untuk mendapatkan jumlah sampel dan jumlah fitur dari bentuk matriks x.
  * x _= x.mean(axis=0) untuk mengurangkan mean dari setiap kolom data sehingga data memiliki mean 0.
  * u, sigma, vt = np.linalg.svd(X, full_matrices=False) untuk memecah matriks x menjadi tiga matriks u, sigma dan vt.

    matriks u adalah matriks ortogonal yang kolom-kolomya adalah vektor singular kiri.

    matriks sigma adalah vektor yang berisi singular values.

    matriks vt adalah ortogonal yang baris-barisnya adalah vektor singular kanan.

  * return (X @ vt.T), (sigma**2) / (n-1) untuk mengembalikan nilai ke dalam fungsi.

    (X @ vt.T) adalah matriks hasil transformasi data asli ke ruang komponen utama.

    (sigma**2) / (n-1) adalah nilai eigen yang digunakan untuk menghitung proporsi variansi.