## **Matriks Invers**


Invers matriks adalah kebalikan (invers) dari sebuah matriks yang apabila matriks tersebut dikalikan dengan inversnya, dia akan  menjadi matriks identitas. Invers matriks dilambangkan dengan $A^-1$. Dan suatu matriks dikatakan memiliki invers jika determinan dari matriks tersebut tidak sama dengan nol.

semisal saya mempunyai matriks persegi A berukuran n x n tidak singular, jika saya mempunyai matrik B dengan ukuran yang sama dengan matriks A maka memenuhi hubungannya:

## AB = BA = $I_n$

lambang ini  $I_n$ melambangkan matriks identitas dengan berukuran n x n, dan perkalian yang dilakukan merupakan perkalian matriks yang umum. Jika hubungan tersebut berlaku, maka matriks B disebut sebagai balikan atau invers dari matriks A, dan akan diberi lambang $A^-1$.




matriks persegi bersifat singular jika nilai dari determinannya 0, selain matriks persegi yang berukuran m x n dan m =/ n tidak memiliki invers

## **Eliminasi gauss-jordan**
merupakan prosedur pemecahan sistem persamaan linier dengan mengubahnya menjadi bentuk matriks eselon baris tereduksi dengan operasi baris elementer

## **sifat-sifat matriks invers dengan eliminasi gauss jordan**

1.  Matriks invers hanya ada jika matriks awal non-singular, yang berarti determinannya tidak sama dengan nol.

2.  jika matriks memiliki invers, maka inversnya adalah satu-satunya.

3. jika A matriks non singular dan B adalah inversnya maka B x A = A x B = I dimana I ini adalah matriks identitas

4. jika A matriks non singular dan B inversnya dan C matriks lain maka
(A X B) X C = A x (B X C) = C

5. matriks non singular A,B dan C dengan ukuran yang sesuai berlaku A x (B + C) = A x B + A x C

6. jika A dan B matriks non singular maka AB memiliki inversnya, ini adalah inversnya $B^-1 A^-1$

7. jika A non singular maka A^T juga non singular dan inversnya adalah $(A^-1)^T$

## **Contoh penyelesaian sistem linier menggunakan matriks invers**

**Persamaan dengan 3 Variabel**

In [90]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

# a = np.array([[2,2,1,1,0,0],[4,2,3,0,1,0],[1,3,-1,0,0,1]])
# print(a)
a = np.array([[1,1,0.5,0.5,0,0],[0,1,-0.5,1,-0.5,0],[0,0,1,5,-2,-2]])
print(a)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [7]:
b = RowScale(a,2,1/2)
print(b)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [3]:
c = RowAdd(b,2,1,1)
print(c)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [4]:
d = RowAdd(c,2,0,-1)
print(d)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [5]:
f = RowScale(d,2,2)
print(f)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [6]:
g = RowAdd(f,1,0,-1)
print(g)

[[ 1.   0.   0.  -5.5  2.5  2. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [7]:
b = np.array([[9],[17],[5]])

c = np.array([[-5.5,2.5,2],[3.5,-1.5,-1],[5,-2,-2]])

print(c@b)

[[3.]
 [1.]
 [1.]]


**Persamaan dengan 4 variabel**

$2x_1 + 0x_2 + 0x_3 + 0x_4 = 2$

$0x_1 + 0x_2 + 4x_3 + 0x_4 = 4$

$0x_1 + 1x_2 + 2x_3 + 0x_4 = 3$

$2x_1 + 0x_2 + 0x_3 + 2x_4 = 4$

\[$
A = \begin{bmatrix}
2 & 0 & 0 & 0 \\
0 & 0 & 4 & 0 \\
0 & 1 & 2 & 0 \\
2 & 0 & 0 & 2
\end{bmatrix}$, $\quad
X = \begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{bmatrix}$, $\quad
B = \begin{bmatrix}
2 \\
4 \\
3 \\
4
\end{bmatrix}$
\]





In [99]:
import numpy as np
a = np.array([[2, 0, 0, 0, 1, 0, 0, 0],
              [0, 0, 4, 0, 0, 1, 0, 0],
              [0, 1, 2, 0, 0, 0, 1, 0],
              [2, 0, 0, 2, 0, 0, 0, 1]])
print(a)

[[2 0 0 0 1 0 0 0]
 [0 0 4 0 0 1 0 0]
 [0 1 2 0 0 0 1 0]
 [2 0 0 2 0 0 0 1]]


In [101]:
A = a[:, 0:4]
print(A)

[[2 0 0 0]
 [0 0 4 0]
 [0 1 2 0]
 [2 0 0 2]]


In [68]:
# mengalikan baris 0 dengan 1/2
b = RowScale(a, 0, 1/2)
print(b)

[[1.  0.  0.  0.  0.5 0.  0.  0. ]
 [0.  0.  4.  0.  0.  1.  0.  0. ]
 [0.  1.  2.  0.  0.  0.  1.  0. ]
 [2.  0.  0.  2.  0.  0.  0.  1. ]]


In [69]:
# menukar baris 1 dan 2
c = RowSwap(b, 1, 2)
print(c)

[[1.  0.  0.  0.  0.5 0.  0.  0. ]
 [0.  1.  2.  0.  0.  0.  1.  0. ]
 [0.  0.  4.  0.  0.  1.  0.  0. ]
 [2.  0.  0.  2.  0.  0.  0.  1. ]]


In [70]:
# menambah baris 1 dengan baris 2 yang sudah dikalikan dengan -1/2
d = RowAdd(c, 2, 1, -1/2)
print(d)

[[ 1.   0.   0.   0.   0.5  0.   0.   0. ]
 [ 0.   1.   0.   0.   0.  -0.5  1.   0. ]
 [ 0.   0.   4.   0.   0.   1.   0.   0. ]
 [ 2.   0.   0.   2.   0.   0.   0.   1. ]]


In [71]:
# mengalikan baris 2 dengan 1/4
e = RowScale(d, 2, 1/4)
print(e)

[[ 1.    0.    0.    0.    0.5   0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -0.5   1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.25  0.    0.  ]
 [ 2.    0.    0.    2.    0.    0.    0.    1.  ]]


In [72]:
# menambahkan baris ke 3 dengan baris 0 yang sudah dikalikan -2
f = RowAdd(e, 0, 3, -2)
print(f)

[[ 1.    0.    0.    0.    0.5   0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -0.5   1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.25  0.    0.  ]
 [ 0.    0.    0.    2.   -1.    0.    0.    1.  ]]


In [73]:
# mengalikan baris ke 3 dengan 1/2
g = RowScale(f, 3, 1/2)
print(g)

[[ 1.    0.    0.    0.    0.5   0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -0.5   1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.25  0.    0.  ]
 [ 0.    0.    0.    1.   -0.5   0.    0.    0.5 ]]


In [123]:
print(g[:, 4:8])
Ain = (g[:, 4:8])
i = A @ Ain
Ain1 = Ain
Ain1

[[ 0.5   0.    0.    0.  ]
 [ 0.   -0.5   1.    0.  ]
 [ 0.    0.25  0.    0.  ]
 [-0.5   0.    0.    0.5 ]]


array([[ 0.5 ,  0.  ,  0.  ,  0.  ],
       [ 0.  , -0.5 ,  1.  ,  0.  ],
       [ 0.  ,  0.25,  0.  ,  0.  ],
       [-0.5 ,  0.  ,  0.  ,  0.5 ]])

In [124]:
# mencari hasil X1, X2, X3, X4
h = np.array([[0.5,0,0,0],[0,-0.5,1,0],[0,0.25,0,0],[-0.5,0,0,0.5]])
k = np.array([[2],[4],[3],[4]])
print(h@k)
sol = h@k
sol
A1 = Ain1@k
A1


[[1.]
 [1.]
 [1.]
 [1.]]


array([[1.],
       [1.],
       [1.],
       [1.]])

In [77]:
# Bukti
h = np.array([[0.5,0,0,0],[0,-0.5,1,0],[0,0.25,0,0],[-0.5,0,0,0.5]])
a = np.array([[2, 0, 0, 0, 1, 0, 0, 0],
              [0, 0, 4, 0, 0, 1, 0, 0],
              [0, 1, 2, 0, 0, 0, 1, 0],
              [2, 0, 0, 2, 0, 0, 0, 1]])
print(j@a)

[[ 1.    0.    0.    0.    0.5   0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -0.5   1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.25  0.    0.  ]
 [ 0.    0.    0.    1.   -0.5   0.    0.    0.5 ]]
